reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LINT_PODSPEC=no
  - FORCE_CARTHAGE_VERSION=yes
  - secure: uPyKTuEdp8aOw4bDrB6ACQkkHzDCTUCnIVraVpGhKulr8GrTQ8Lkwl6HONDYR7iC+U9PCGscbxcFumuUv4DkYrD4yIjdC5KOsilOr381eG1XDpXxFW5vZqBO4zDcxr7xemrhZ/h5qx07jXKU2dzfthe0xl3+2fyYrQinglTVQ9IVJzCAqANPS2/drU+dRInLm9ndhsxjcWeaZu+G6M5uwg/f4drUw0OwL05/BN5oDfI4jB02LDwJJXUWdDDf+CKC0/kMrFWgFTo1MWRnKgJwKpODdNb+AXWMIQnqnsNyv4hfwx9H2Y6Pj+/v32+zAzeJtzzBLlB14WDwPzEy05+LgFuxbQjcUDMipcwjL+rceQlBIe3L5hzu7g99KyukMjUejZi9o+xxN2ri001FbZGpjjl/0NcCKzbKVUErWFldWCuk43gHjrTHtgGr5XjJaBnd4tflwfgpZgRRxzPiXJiILerf9YhJnWKkxSpTgCI3CdWWkxqWKpx1mN5qOall4DNfyp1tIBj1EgDJjAwSbS12IBR6BWGrKb8VApeDpOlq3Bx9VTUvSosft2ufamTSbh8gYSjtOprRQ2b/Qv4gtW7BvRAlSwA8jkEMXG/K/LOdq8maWGeWKAx/AZMLlmxK2Lnyk5gICE7Sy07UjQ4yE9Ey/QmtFJRmnyC1eZZ5MmpX1X8=
  matrix:
  - SCHEME="Guardian" IOS_DESTINATION_VERSION="9.0" CARTHAGE_BUILD_PLATFORM="iOS"
  - SCHEME="Guardian" IOS_DESTINATION_VERSION="9.1" CARTHAGE_BUILD_PLATFORM="iOS"
  - SCHEME="Guardian" IOS_DESTINATION_VERSION="9.2" CARTHAGE_BUILD_PLATFORM="iOS"
  - SCHEME="Guardian" IOS_DESTINATION_VERSION="9.3" CARTHAGE_BUILD_PLATFORM="iOS"
before_install: true
install: true
script:
- script/cibuild
branches:
  only:
  - master
